export const LOGIN_REQUEST = 'ALL_USERS_REQUEST';
export const LOGIN_SUCCESS = 'ALL_USERS_SUCCESS';
export const LOGIN_FAIL = 'ALL_USERS_FAIL';

export const USERS_DETAILS_REQUEST = 'USERS_DETAILS_REQUEST';
export const USERS_DETAILS_SUCCESS = 'USERS_DETAILS_SUCCESS';
export const USERS_DETAILS_FAIL = 'USERS_DETAILS_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';